"""Standalone Python steps: a LambdaOp that no LLM consumes.

A LambdaOp read by an LLM is inlined into that LLM's FlowMesh task as a
``graph_template`` function. A LambdaOp that is an output, or that feeds only
other LambdaOps, runs as its own FlowMesh ``python`` task: the caller's code in
a per-task container with no network and an unprivileged uid (FlowMesh
``worker/executors/python_executor.py``), never in-process on a worker.

The task's code is a generated wrapper around the caller's function. It keeps
the LambdaOp contract — ``fn(row: tuple[str, ...]) -> str`` applied per row —
by reading each upstream stage's mounted ``results.json`` (its ``items[].output``
column) or a literal column from an ``InputOp``/``DataOp``, broadcasting
length-1 columns, and returning ``{"items": [{"output": ...}, ...]}`` so the step
reads like any other items-producing node downstream and in outputs.
"""

import json
from typing import Any

TASK_TYPE = "python"
BACKEND = "python"
DEFAULT_TIMEOUT_SECONDS = 600

# Column plan entries: {"kind": "stage", "name": <upstream node id>} or
# {"kind": "literal", "values": [...]}.
ColumnPlan = list[dict[str, Any]]

_WRAPPER = """\
# Generated by Lumilake for LambdaOp {op_id!r}. The caller's function is
# _USER_CODE; everything else adapts it to a FlowMesh python task.
import json
import os
import types

_USER_CODE = {code!r}
_PLAN = json.loads({plan!r})


def _materialize():
    src = _USER_CODE.strip()
    if src.startswith("lambda"):
        return eval(src, {{}})
    namespace = {{}}
    exec(src, namespace)
    fns = [v for k, v in namespace.items()
           if isinstance(v, types.FunctionType) and not k.startswith("__")]
    if len(fns) != 1:
        raise ValueError(
            "LambdaOp code must define exactly one function, found %d" % len(fns)
        )
    return fns[0]


def _text(value):
    return value if isinstance(value, str) else json.dumps(value)


def _column(entry, inputs):
    if entry["kind"] == "literal":
        return [_text(v) for v in entry["values"]]
    with open(os.path.join(inputs[entry["name"]], "results.json")) as fh:
        envelope = json.load(fh)
    result = envelope.get("result", envelope)
    items = result.get("items")
    if items is None and isinstance(result.get("value"), dict):
        items = result["value"].get("items")
    if items is None and isinstance(result.get("text"), str):
        items = [{{"output": result["text"]}}]
    if not isinstance(items, list):
        raise ValueError("upstream %r produced no items" % entry["name"])
    return [_text(i["output"]) if isinstance(i, dict) and "output" in i else _text(i)
            for i in items]


def main(inputs):
    fn = _materialize()
    columns = [_column(entry, inputs) for entry in _PLAN]
    n = max((len(c) for c in columns), default=1)
    for entry, col in zip(_PLAN, columns):
        if len(col) not in (1, n):
            raise ValueError(
                "input %r has %d rows; expected 1 or %d"
                % (entry.get("name", "literal"), len(col), n)
            )
    rows = [tuple(c[0] if len(c) == 1 else c[i] for c in columns) for i in range(n)]
    return {{"items": [{{"output": _text(fn(row))}} for row in rows]}}
"""


def wrapper_source(op_id: str, user_code: str, plan: ColumnPlan) -> str:
    """The python-task code for one standalone LambdaOp."""
    return _WRAPPER.format(op_id=op_id, code=user_code, plan=json.dumps(plan))


def flowmesh_spec(data_spec: dict[str, Any], dependencies: list[str]) -> dict[str, Any]:
    """The FlowMesh ``python`` task spec for a runtime python step."""
    spec: dict[str, Any] = {
        "taskType": TASK_TYPE,
        "code": data_spec["code"],
        "entrypoint": "main",
        "timeoutSeconds": data_spec.get("timeout_s", DEFAULT_TIMEOUT_SECONDS),
    }
    stages = [s for s in data_spec.get("stages", []) if s in dependencies]
    if stages:
        spec["inputs"] = [{"stage": s} for s in stages]
    return spec
