"""Standalone Python steps: a LambdaOp that no LLM consumes.

A LambdaOp read by an LLM is inlined into that LLM's FlowMesh task as a
``graph_template`` function. A LambdaOp that is an output, or that feeds only
other LambdaOps, runs as its own FlowMesh ``python`` task: the caller's code in
a per-task container with no network and an unprivileged uid (FlowMesh
``worker/executors/python_executor.py``), never in the Lumilake server process.
That container is the execution boundary for submitted code.

The task's code is a generated wrapper around the caller's function. It embeds
``utils/lambda_runtime.py`` verbatim, so the function is materialized with the
same namespace contract the server validates against. It keeps the LambdaOp
contract — ``fn(row: tuple[str, ...]) -> str`` applied per row — by reading each
upstream stage's mounted ``results.json`` (its ``items[].output`` column) or a
literal column from an ``InputOp``/``DataOp``, broadcasting length-1 columns,
and returning ``{"items": [{"output": ...}, ...]}`` so the step reads like any
other items-producing node downstream and in outputs.

A runtime step stores its column plan in ``data_spec["plan"]`` with stage
references under the ``node`` key. The wrapper and the task's ``inputs`` are
generated from that plan when the node is exported to FlowMesh, so they carry
the node ids the graph has at that point, prefixed or not.
"""

import inspect
import json
from typing import Any

from lumilake_server.utils import lambda_runtime

TASK_TYPE = "python"
BACKEND = "python"
DEFAULT_TIMEOUT_SECONDS = 600

# Column plan entries: {"kind": "stage", "node": <upstream node id>} or
# {"kind": "literal", "values": [...]}.
ColumnPlan = list[dict[str, Any]]

_WRAPPER = """\
# Generated by Lumilake for LambdaOp {op_id!r}. The caller's function is
# _USER_CODE; everything else adapts it to a FlowMesh python task.
{runtime}
import os

_USER_CODE = {code!r}
_PLAN = json.loads({plan!r})


def _text(value):
    return value if isinstance(value, str) else json.dumps(value)


def _column(entry, inputs):
    if entry["kind"] == "literal":
        return [_text(v) for v in entry["values"]]
    with open(os.path.join(inputs[entry["node"]], "results.json")) as fh:
        envelope = json.load(fh)
    result = envelope.get("result", envelope)
    items = result.get("items")
    if items is None and isinstance(result.get("value"), dict):
        items = result["value"].get("items")
    if items is None and isinstance(result.get("text"), str):
        items = [{{"output": result["text"]}}]
    if not isinstance(items, list):
        raise ValueError("upstream %r produced no items" % entry["node"])
    return [_text(i["output"]) if isinstance(i, dict) and "output" in i else _text(i)
            for i in items]


def main(inputs):
    fn = materialize(_USER_CODE)
    columns = [_column(entry, inputs) for entry in _PLAN]
    n = max((len(c) for c in columns), default=1)
    for entry, col in zip(_PLAN, columns):
        if len(col) not in (1, n):
            raise ValueError(
                "input %r has %d rows; expected 1 or %d"
                % (entry.get("node", "literal"), len(col), n)
            )
    rows = [tuple(c[0] if len(c) == 1 else c[i] for c in columns) for i in range(n)]
    return {{"items": [{{"output": _text(fn(row))}} for row in rows]}}
"""


def wrapper_source(op_id: str, user_code: str, plan: ColumnPlan) -> str:
    """The python-task code for one standalone LambdaOp."""
    return _WRAPPER.format(
        op_id=op_id,
        runtime=inspect.getsource(lambda_runtime),
        code=user_code,
        plan=json.dumps(plan),
    )


def flowmesh_spec(node_id: str, data_spec: dict[str, Any]) -> dict[str, Any]:
    """The FlowMesh ``python`` task spec for a runtime python step."""
    plan: ColumnPlan = data_spec["plan"]
    spec: dict[str, Any] = {
        "taskType": TASK_TYPE,
        "code": wrapper_source(node_id, data_spec["code"], plan),
        "entrypoint": "main",
        "timeoutSeconds": data_spec["timeout_s"],
    }
    stages = list(
        dict.fromkeys(entry["node"] for entry in plan if entry["kind"] == "stage")
    )
    if stages:
        spec["inputs"] = [{"stage": stage} for stage in stages]
    if "memory_mb" in data_spec:
        spec["resources"] = {"hardware": {"memory": f"{data_spec['memory_mb']}Mi"}}
    return spec
