"""Standalone Python steps: a LambdaOp that no LLM consumes.

A LambdaOp read by an LLM is inlined into that LLM's FlowMesh task as a
``graph_template`` function. A LambdaOp that is an output, or that feeds only
other LambdaOps, runs as its own FlowMesh ``python`` task: the caller's code in
a per-task container with no network and an unprivileged uid (FlowMesh
``worker/executors/python_executor.py``), never in the Lumilake server process.
That container is the execution boundary for submitted code.

The task's code is a generated wrapper around the caller's function. It embeds
``utils/lambda_runtime.py`` verbatim, so the function is materialized with the
same namespace contract the server validates against. It keeps the LambdaOp
contract — ``fn(row: tuple[str, ...]) -> str`` applied per row — by reading each
upstream stage's mounted ``results.json`` (its ``items[].output`` column) or a
literal column from an ``InputOp``/``DataOp``, broadcasting length-1 columns,
and returning ``{"items": [{"output": ...}, ...]}`` so the step reads like any
other items-producing node downstream and in outputs.

A runtime step stores its column plan in ``data_spec["plan"]`` with stage
references under the ``node`` key. The wrapper and the task's ``inputs`` are
generated from that plan when the node is exported to FlowMesh, so they carry
the node ids the graph has at that point, prefixed or not.

Two reshape modes never call user code. ``flatten`` turns a per-row VLM's
upstream items (one per image, row-major) into one rendered prompt per image,
emitting ``{"output": prompt, "row": i}``. ``regroup`` groups those prompts'
outputs back to one item per symbol, emitting ``{"output": [row outputs]}``.
Both read their columns through the same ``_column``/``_walk_path`` helpers;
only ``flatten`` renders the rowwise template with ``_TEMPLATE``.
"""

import inspect
import json
from typing import Any

from lumilake_server.utils import lambda_runtime

TASK_TYPE = "python"
BACKEND = "python"
DEFAULT_TIMEOUT_SECONDS = 600

# Column plan entries: {"kind": "stage", "node": <upstream node id>} or
# {"kind": "literal", "values": [...]}.
ColumnPlan = list[dict[str, Any]]

_HELPERS = """\

def _text(value):
    return value if isinstance(value, str) else json.dumps(value)


def _walk_path(value, parts, where):
    for idx, part in enumerate(parts):
        if isinstance(value, str):
            try:
                value = json.loads(value)
            except ValueError:
                raise ValueError("bad JSON at %s" % where)
        if isinstance(value, dict) and list(value) == ["df"] and isinstance(
            value["df"], str
        ):
            try:
                table = json.loads(value["df"])
            except ValueError:
                raise ValueError("bad JSON at %s" % where)
            if part not in table:
                raise ValueError("missing %r at %s" % (part, where))
            column = table[part]
            if not isinstance(column, dict):
                raise ValueError("missing %r at %s" % (part, where))
            value = [column[k] for k in sorted(column, key=int)]
            rest = parts[idx + 1 :]
            if rest:
                return [_walk_path(v, rest, where) for v in value]
            return value
        if isinstance(value, dict) and part in value:
            value = value[part]
        else:
            raise ValueError("missing %r at %s" % (part, where))
    return value


def _column(entry, inputs, text):
    if entry["kind"] == "literal":
        return [text(v) for v in entry["values"]]
    with open(os.path.join(inputs[entry["node"]], "results.json")) as fh:
        envelope = json.load(fh)
    result = envelope.get("result", envelope)
    items = result.get("items")
    if items is None and isinstance(result.get("value"), dict):
        items = result["value"].get("items")
    if items is None and isinstance(result.get("text"), str):
        items = [{{"output": result["text"]}}]
    if not isinstance(items, list):
        raise ValueError("upstream %r produced no items" % entry["node"])
    path = entry.get("path")
    if path:
        parts = path.split(".")
        return [
            _walk_path(i, parts, "%s item %d path %s" % (entry["node"], idx, path))
            for idx, i in enumerate(items)
        ]
    return [text(i["output"]) if isinstance(i, dict) and "output" in i else text(i)
            for i in items]
"""

_PRELUDE = """\
# Generated by Lumilake for LambdaOp {op_id!r}. The caller's function is
# _USER_CODE; everything else adapts it to a FlowMesh python task.
{runtime}
import os

_USER_CODE = {code!r}
_FN_NAME = {fn_name!r}
_PLAN = json.loads({plan!r})
""" + _HELPERS

_RESHAPE_PRELUDE = """\
# Generated by Lumilake for {op_id!r}: a flatten/regroup reshape step.
import json
import os

_NODE = {op_id!r}
_PLAN = json.loads({plan!r})
""" + _HELPERS

_FLATTEN_MAIN = """\

_TEMPLATE = {template!r}

def main(inputs):
    columns = [_column(entry, inputs, _text) for entry in _PLAN]
    grouped = [c for c, e in zip(columns, _PLAN) if e.get("grouped")]
    row_level = [c for c, e in zip(columns, _PLAN) if not e.get("grouped")]
    n = len(grouped[0])
    group_sizes = [len(g) for g in grouped[0]]
    for entry, col in zip(_PLAN, columns):
        label = entry.get("label")
        if entry.get("grouped"):
            if len(col) != n:
                raise ValueError(
                    "%s: flatten grouped column %r has %d groups; expected %d"
                    % (_NODE, label, len(col), n)
                )
            for i, group in enumerate(col):
                if len(group) != group_sizes[i]:
                    raise ValueError(
                        "%s: flatten grouped column %r row %d has %d values; "
                        "expected %d" % (_NODE, label, i, len(group), group_sizes[i])
                    )
        elif len(col) not in (1, n):
            raise ValueError(
                "%s: flatten row-level column %r has %d values; expected 1 or %d"
                % (_NODE, label, len(col), n)
            )
    items = []
    for i in range(n):
        size = group_sizes[i]
        for j in range(size):
            values = {{}}
            for entry, col in zip(_PLAN, columns):
                if entry is _PLAN[0]:
                    # The image entry (always first) is the group boundary; its
                    # content is never rendered into the prompt.
                    continue
                label = entry.get("label")
                if entry.get("grouped"):
                    values[label] = col[i][j]
                else:
                    values[label] = col[i] if len(col) == n else col[0]
            prompt = _TEMPLATE.format_map(
                {{k: _text(v) for k, v in values.items()}}
            )
            items.append({{"output": prompt, "row": i}})
    return {{"items": items}}
"""

_REGROUP_MAIN = """\

def main(inputs):
    columns = [_column(entry, inputs, _text) for entry in _PLAN]
    values = columns[0]
    rows = columns[1]
    groups = columns[2]
    n = len(groups)
    if len(values) != len(rows):
        raise ValueError(
            "%s: regroup has %d outputs but %d rows" % (_NODE, len(values), len(rows))
        )
    result = [[] for _ in range(n)]
    for value, row in zip(values, rows):
        if not isinstance(row, int):
            raise ValueError("%s: regroup row %r is not an integer" % (_NODE, row))
        if not 0 <= row < n:
            raise ValueError(
                "%s: regroup row %d out of range for %d symbols" % (_NODE, row, n)
            )
        result[row].append(value)
    for r in range(n):
        if len(result[r]) != len(groups[r]):
            raise ValueError(
                "%s: regroup row %d has %d outputs; expected %d"
                % (_NODE, r, len(result[r]), len(groups[r]))
            )
    return {{"items": [{{"output": result[r]}} for r in range(n)]}}
"""

_ROW_MAIN = """\

def main(inputs):
    fn = materialize(_USER_CODE, _FN_NAME)
    columns = [_column(entry, inputs, _text) for entry in _PLAN]
    n = max((len(c) for c in columns), default=1)
    for entry, col in zip(_PLAN, columns):
        if len(col) not in (1, n):
            raise ValueError(
                "input %r has %d rows; expected 1 or %d"
                % (entry.get("node", "literal"), len(col), n)
            )
    rows = [tuple(c[0] if len(c) == 1 else c[i] for c in columns) for i in range(n)]
    return {{"items": [{{"output": _text(fn(row))}} for row in rows]}}
"""

_LIST_MAIN = """\

def main(inputs):
    fn = materialize(_USER_CODE, _FN_NAME)
    columns = [_column(entry, inputs, lambda v: v) for entry in _PLAN]
    values = fn(tuple(columns))
    return {{"items": [{{"output": v}} for v in values]}}
"""

_ALIGNED_MAIN = """\

def main(inputs):
    fn = materialize(_USER_CODE, _FN_NAME)
    columns = [_column(entry, inputs, lambda v: v) for entry in _PLAN]
    values = fn(tuple(columns))
    n = max((len(c) for c in columns), default=0)
    if len(values) != n:
        raise ValueError(
            "aligned lambda {op_id!r} returned %d values for %d rows"
            % (len(values), n)
        )
    return {{"items": [{{"output": v}} for v in values]}}
"""


def flatten_source(node_id: str, plan: ColumnPlan, template: str) -> str:
    """The python-task code for a flatten step: one rendered prompt per image."""
    return (_RESHAPE_PRELUDE + _FLATTEN_MAIN).format(
        op_id=node_id,
        plan=json.dumps(plan),
        template=template,
    )


def regroup_source(node_id: str, plan: ColumnPlan) -> str:
    """The python-task code for a regroup step: outputs back to one item per
    symbol."""
    return (_RESHAPE_PRELUDE + _REGROUP_MAIN).format(
        op_id=node_id,
        plan=json.dumps(plan),
    )


def wrapper_source(
    op_id: str,
    fn_name: str,
    user_code: str,
    plan: ColumnPlan,
    mode: str = "row",
) -> str:
    """The python-task code for one standalone LambdaOp."""
    if mode == "list":
        main = _LIST_MAIN
    elif mode == "aligned":
        main = _ALIGNED_MAIN
    else:
        main = _ROW_MAIN
    return (_PRELUDE + main).format(
        op_id=op_id,
        runtime=inspect.getsource(lambda_runtime),
        code=user_code,
        fn_name=fn_name,
        plan=json.dumps(plan),
    )


def flowmesh_spec(node_id: str, data_spec: dict[str, Any]) -> dict[str, Any]:
    """The FlowMesh ``python`` task spec for a runtime python step."""
    plan: ColumnPlan = data_spec["plan"]
    mode = data_spec.get("mode", "row")
    if mode == "flatten":
        code = flatten_source(node_id, plan, data_spec["template"])
    elif mode == "regroup":
        code = regroup_source(node_id, plan)
    else:
        code = wrapper_source(
            node_id, data_spec["fn_name"], data_spec["code"], plan, mode
        )
    spec: dict[str, Any] = {
        "taskType": TASK_TYPE,
        "code": code,
        "entrypoint": "main",
        "timeoutSeconds": data_spec["timeout_s"],
    }
    stages = list(
        dict.fromkeys(entry["node"] for entry in plan if entry["kind"] == "stage")
    )
    if stages:
        spec["inputs"] = [{"stage": stage} for stage in stages]
    if "memory_mb" in data_spec:
        spec["resources"] = {"hardware": {"memory": f"{data_spec['memory_mb']}Mi"}}
    return spec
