"""Generate the server image requirements file from pyproject.toml + uv.lock.

The Lumilake server runs in a Docker image that does NOT consume the
workspace lockfile directly. Instead, the image installs the published
``lumilake-sdk`` / ``lumilake-hook`` interface wheels plus a flat
``requirements.txt`` of runtime dependencies for ``src/lumilake_server/``.

This script enumerates the complete dependency closure of the
``server-runtime`` dependency group, pinned to the exact versions resolved
by ``uv.lock``. The Docker image installs local workspace wheels with
``--no-deps`` so all third-party package resolution flows through this
single pinned file.

Run with no arguments to check for drift against the committed file;
run with ``--write`` to regenerate it in place.
"""

import argparse
import difflib
import subprocess  # nosec B404: pinned argv, no shell
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SERVER_REQ = REPO_ROOT / "src" / "lumilake_server" / "requirements.txt"

SERVER_GROUPS: list[str] = ["server-runtime"]

HEADER = (
    "# AUTO-GENERATED by scripts/dev/sync_requirements.py — do not edit by hand.\n"
    "# Regenerate with: uv run scripts/dev/sync_requirements.py --write\n"
)


def _uv_export(groups: list[str]) -> list[str]:
    cmd = [
        "uv",
        "export",
        "--frozen",
        "--no-dev",
        "--no-default-groups",
        "--no-hashes",
        "--no-emit-project",
        "--format",
        "requirements-txt",
    ]
    for group in groups:
        cmd += ["--group", group]
    result = subprocess.run(  # nosec B603
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, check=True
    )
    pins: list[str] = []
    for raw in result.stdout.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-e "):
            continue
        pins.append(line)
    return pins


def render(groups: list[str]) -> str:
    lines = sorted(_uv_export(groups), key=str.lower)
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Overwrite the committed requirements file with generated output.",
    )
    args = parser.parse_args()

    targets: list[tuple[Path, str]] = [
        (SERVER_REQ, render(SERVER_GROUPS)),
    ]

    mismatches: list[str] = []
    for path, rendered in targets:
        rel = path.relative_to(REPO_ROOT)
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered)
            print(f"Wrote {rel}")
            continue
        current = path.read_text() if path.exists() else ""
        if current != rendered:
            mismatches.append(str(rel))
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(rel),
                tofile=f"{rel} (generated)",
                lineterm="",
            )
            sys.stdout.write("\n".join(diff) + "\n")

    if mismatches and not args.write:
        print("\nMismatched requirements files:")
        for path_str in mismatches:
            print(f"- {path_str}")
        print("\nRun `uv run scripts/dev/sync_requirements.py --write` to regenerate.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
