"""Generate the server image requirements file from pyproject.toml + uv.lock.

The Lumilake server runs in a Docker image that does NOT consume the
workspace lockfile directly. Instead, the image installs the published
``lumilake-sdk`` interface wheel plus a flat ``requirements.txt`` of
runtime dependencies for ``src/lumilake_server/``.

This script enumerates the DIRECT dependencies of the
``server-runtime`` dependency group, pinned to the exact versions
resolved by ``uv.lock``. Transitives are deliberately not listed so that
the same pin set is reusable across architectures (amd64 + arm64).

Run with no arguments to check for drift against the committed file;
run with ``--write`` to regenerate it in place.
"""

import argparse
import difflib
import re
import subprocess  # nosec B404: pinned argv, no shell
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = REPO_ROOT / "pyproject.toml"
SERVER_REQ = REPO_ROOT / "src" / "lumilake_server" / "requirements.txt"

SERVER_GROUPS: list[str] = ["server-runtime"]

HEADER = (
    "# AUTO-GENERATED by scripts/dev/sync_requirements.py — do not edit by hand.\n"
    "# Regenerate with: uv run scripts/dev/sync_requirements.py --write\n"
)

_PKG_RE = re.compile(r"^([A-Za-z0-9_.-]+)(\[[^\]]+\])?(?:\s*[@<>=!~].*)?$")


def _direct_deps(groups: list[str]) -> dict[str, str]:
    with PYPROJECT.open("rb") as f:
        data = tomllib.load(f)
    dependency_groups = data["dependency-groups"]
    deps: dict[str, str] = {}
    for group in groups:
        if group not in dependency_groups:
            raise SystemExit(
                f"Group {group!r} not found in pyproject.toml [dependency-groups]."
            )
        for spec in dependency_groups[group]:
            if not isinstance(spec, str):
                raise SystemExit(
                    f"Group {group!r} contains an include or non-string entry. "
                    "Use leaf runtime groups when generating requirements."
                )
            m = _PKG_RE.match(spec.strip())
            if not m:
                continue
            name = m.group(1).lower().replace("_", "-")
            marker = m.group(2) or ""
            if marker and len(marker) > len(deps.get(name, "")):
                deps[name] = marker
            else:
                deps.setdefault(name, marker)
    return deps


def _uv_export(groups: list[str]) -> list[str]:
    cmd = [
        "uv",
        "export",
        "--frozen",
        "--no-dev",
        "--no-default-groups",
        "--no-hashes",
        "--no-emit-project",
        "--format",
        "requirements-txt",
    ]
    for group in groups:
        cmd += ["--group", group]
    result = subprocess.run(  # nosec B603
        cmd, cwd=REPO_ROOT, capture_output=True, text=True, check=True
    )
    pins: list[str] = []
    for raw in result.stdout.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("-e "):
            continue
        pins.append(line)
    return pins


def _line_pkg(line: str) -> str:
    head = line.split(";", 1)[0].strip()
    m = re.match(r"^([A-Za-z0-9_.-]+)", head)
    if not m:
        return ""
    return m.group(1).lower().replace("_", "-")


def _filter_direct(pins: list[str], keep: dict[str, str]) -> list[str]:
    out: list[str] = []
    for pin in pins:
        name = _line_pkg(pin)
        if name not in keep:
            continue
        marker = keep[name]
        if not marker:
            out.append(pin)
            continue
        head, sep, tail = pin.partition("==")
        out.append(f"{head.strip()}{marker}{sep}{tail.strip()}" if sep else pin)
    return sorted(out, key=str.lower)


def render(groups: list[str]) -> str:
    direct = _direct_deps(groups)
    lines = _filter_direct(_uv_export(groups), direct)
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="Overwrite the committed requirements file with generated output.",
    )
    args = parser.parse_args()

    targets: list[tuple[Path, str]] = [
        (SERVER_REQ, render(SERVER_GROUPS)),
    ]

    mismatches: list[str] = []
    for path, rendered in targets:
        rel = path.relative_to(REPO_ROOT)
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered)
            print(f"Wrote {rel}")
            continue
        current = path.read_text() if path.exists() else ""
        if current != rendered:
            mismatches.append(str(rel))
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(rel),
                tofile=f"{rel} (generated)",
                lineterm="",
            )
            sys.stdout.write("\n".join(diff) + "\n")

    if mismatches and not args.write:
        print("\nMismatched requirements files:")
        for path_str in mismatches:
            print(f"- {path_str}")
        print("\nRun `uv run scripts/dev/sync_requirements.py --write` to regenerate.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
